"""Assigned identity: the neutral `source` / `source_key` columns and their searches.

`req-compliance-core-identity` (Issue# 8 - tap-plugin-compliance-core). The five
producer-minted types gain the two columns their `NATURAL_KEY` declares, plus the
composite index core generates from that declaration. `compliance_context` needs no
index: it keys on `regime`, a single field that is already `db_index`.

Additive and backfill-free by design. Existing rows carry `""` in both columns, which
is a HOLE, not a match — the generated search answers "not found" for them rather than
collapsing every pre-adoption row into one. Nothing resolves against these declarations
until a producer emits a ref, which takes a release of this plugin plus a pin bump in
the consumer.
"""

# Generated by Django 6.0.8 on 2026-09-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance_core", "0003_retire_renamed_edge_types"),
        ("tap_grid", "0005_entity_natural_key_clear"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceartifact",
            name="source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="complianceartifact",
            name="source_key",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="complianceboundary",
            name="source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="complianceboundary",
            name="source_key",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="complianceevidence",
            name="source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="complianceevidence",
            name="source_key",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="complianceexception",
            name="source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="complianceexception",
            name="source_key",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="compliancefinding",
            name="source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="compliancefinding",
            name="source_key",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="historicalcomplianceartifact",
            name="source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="historicalcomplianceartifact",
            name="source_key",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="historicalcomplianceboundary",
            name="source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="historicalcomplianceboundary",
            name="source_key",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="historicalcomplianceevidence",
            name="source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="historicalcomplianceevidence",
            name="source_key",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="historicalcomplianceexception",
            name="source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="historicalcomplianceexception",
            name="source_key",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="historicalcompliancefinding",
            name="source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="historicalcompliancefinding",
            name="source_key",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddIndex(
            model_name="complianceartifact",
            index=models.Index(
                fields=["source", "source_key"], name="nk_compliance_core__co_5ad32ed"
            ),
        ),
        migrations.AddIndex(
            model_name="complianceboundary",
            index=models.Index(
                fields=["source", "source_key"], name="nk_compliance_core__co_d7043ed"
            ),
        ),
        migrations.AddIndex(
            model_name="complianceevidence",
            index=models.Index(
                fields=["source", "source_key"], name="nk_compliance_core__co_e215e98"
            ),
        ),
        migrations.AddIndex(
            model_name="complianceexception",
            index=models.Index(
                fields=["source", "source_key"], name="nk_compliance_core__co_83bc3a7"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancefinding",
            index=models.Index(
                fields=["source", "source_key"], name="nk_compliance_core__co_e6a7643"
            ),
        ),
    ]
